<?php

use App\Models\Upazila;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
  /**
   * Run the migrations.
   *
   * @return void
   */
  public function up()
  {
    Schema::create(with(new Upazila)->getTable(), function (Blueprint $table) {
      $table->id();
      $table->unsignedBigInteger('district_id');
      $table->string('name');
      $table->string('name_bn')->nullable();
      $table->text('url')->nullable();
      $table->timestamps();
    });

    $upazilas = array(
      array('id' => '1', 'district_id' => '1', 'name' => 'Debidwar', 'name_bn' => 'দেবিদ্বার', 'url' => 'debidwar.comilla.gov.bd'),
      array('id' => '2', 'district_id' => '1', 'name' => 'Barura', 'name_bn' => 'বরুড়া', 'url' => 'barura.comilla.gov.bd'),
      array('id' => '3', 'district_id' => '1', 'name' => 'Brahmanpara', 'name_bn' => 'ব্রাহ্মণপাড়া', 'url' => 'brahmanpara.comilla.gov.bd'),
      array('id' => '4', 'district_id' => '1', 'name' => 'Chandina', 'name_bn' => 'চান্দিনা', 'url' => 'chandina.comilla.gov.bd'),
      array('id' => '5', 'district_id' => '1', 'name' => 'Chauddagram', 'name_bn' => 'চৌদ্দগ্রাম', 'url' => 'chauddagram.comilla.gov.bd'),
      array('id' => '6', 'district_id' => '1', 'name' => 'Daudkandi', 'name_bn' => 'দাউদকান্দি', 'url' => 'daudkandi.comilla.gov.bd'),
      array('id' => '7', 'district_id' => '1', 'name' => 'Homna', 'name_bn' => 'হোমনা', 'url' => 'homna.comilla.gov.bd'),
      array('id' => '8', 'district_id' => '1', 'name' => 'Laksam', 'name_bn' => 'লাকসাম', 'url' => 'laksam.comilla.gov.bd'),
      array('id' => '9', 'district_id' => '1', 'name' => 'Muradnagar', 'name_bn' => 'মুরাদনগর', 'url' => 'muradnagar.comilla.gov.bd'),
      array('id' => '10', 'district_id' => '1', 'name' => 'Nangalkot', 'name_bn' => 'নাঙ্গলকোট', 'url' => 'nangalkot.comilla.gov.bd'),
      array('id' => '11', 'district_id' => '1', 'name' => 'Comilla Sadar', 'name_bn' => 'কুমিল্লা সদর', 'url' => 'comillasadar.comilla.gov.bd'),
      array('id' => '12', 'district_id' => '1', 'name' => 'Meghna', 'name_bn' => 'মেঘনা', 'url' => 'meghna.comilla.gov.bd'),
      array('id' => '13', 'district_id' => '1', 'name' => 'Monohargonj', 'name_bn' => 'মনোহরগঞ্জ', 'url' => 'monohargonj.comilla.gov.bd'),
      array('id' => '14', 'district_id' => '1', 'name' => 'Sadarsouth', 'name_bn' => 'সদর দক্ষিণ', 'url' => 'sadarsouth.comilla.gov.bd'),
      array('id' => '15', 'district_id' => '1', 'name' => 'Titas', 'name_bn' => 'তিতাস', 'url' => 'titas.comilla.gov.bd'),
      array('id' => '16', 'district_id' => '1', 'name' => 'Burichang', 'name_bn' => 'বুড়িচং', 'url' => 'burichang.comilla.gov.bd'),
      array('id' => '17', 'district_id' => '1', 'name' => 'Lalmai', 'name_bn' => 'লালমাই', 'url' => 'lalmai.comilla.gov.bd'),
      array('id' => '18', 'district_id' => '2', 'name' => 'Chhagalnaiya', 'name_bn' => 'ছাগলনাইয়া', 'url' => 'chhagalnaiya.feni.gov.bd'),
      array('id' => '19', 'district_id' => '2', 'name' => 'Feni Sadar', 'name_bn' => 'ফেনী সদর', 'url' => 'sadar.feni.gov.bd'),
      array('id' => '20', 'district_id' => '2', 'name' => 'Sonagazi', 'name_bn' => 'সোনাগাজী', 'url' => 'sonagazi.feni.gov.bd'),
      array('id' => '21', 'district_id' => '2', 'name' => 'Fulgazi', 'name_bn' => 'ফুলগাজী', 'url' => 'fulgazi.feni.gov.bd'),
      array('id' => '22', 'district_id' => '2', 'name' => 'Parshuram', 'name_bn' => 'পরশুরাম', 'url' => 'parshuram.feni.gov.bd'),
      array('id' => '23', 'district_id' => '2', 'name' => 'Daganbhuiyan', 'name_bn' => 'দাগনভূঞা', 'url' => 'daganbhuiyan.feni.gov.bd'),
      array('id' => '24', 'district_id' => '3', 'name' => 'Brahmanbaria Sadar', 'name_bn' => 'ব্রাহ্মণবাড়িয়া সদর', 'url' => 'sadar.brahmanbaria.gov.bd'),
      array('id' => '25', 'district_id' => '3', 'name' => 'Kasba', 'name_bn' => 'কসবা', 'url' => 'kasba.brahmanbaria.gov.bd'),
      array('id' => '26', 'district_id' => '3', 'name' => 'Nasirnagar', 'name_bn' => 'নাসিরনগর', 'url' => 'nasirnagar.brahmanbaria.gov.bd'),
      array('id' => '27', 'district_id' => '3', 'name' => 'Sarail', 'name_bn' => 'সরাইল', 'url' => 'sarail.brahmanbaria.gov.bd'),
      array('id' => '28', 'district_id' => '3', 'name' => 'Ashuganj', 'name_bn' => 'আশুগঞ্জ', 'url' => 'ashuganj.brahmanbaria.gov.bd'),
      array('id' => '29', 'district_id' => '3', 'name' => 'Akhaura', 'name_bn' => 'আখাউড়া', 'url' => 'akhaura.brahmanbaria.gov.bd'),
      array('id' => '30', 'district_id' => '3', 'name' => 'Nabinagar', 'name_bn' => 'নবীনগর', 'url' => 'nabinagar.brahmanbaria.gov.bd'),
      array('id' => '31', 'district_id' => '3', 'name' => 'Bancharampur', 'name_bn' => 'বাঞ্ছারামপুর', 'url' => 'bancharampur.brahmanbaria.gov.bd'),
      array('id' => '32', 'district_id' => '3', 'name' => 'Bijoynagar', 'name_bn' => 'বিজয়নগর', 'url' => 'bijoynagar.brahmanbaria.gov.bd    '),
      array('id' => '33', 'district_id' => '4', 'name' => 'Rangamati Sadar', 'name_bn' => 'রাঙ্গামাটি সদর', 'url' => 'sadar.rangamati.gov.bd'),
      array('id' => '34', 'district_id' => '4', 'name' => 'Kaptai', 'name_bn' => 'কাপ্তাই', 'url' => 'kaptai.rangamati.gov.bd'),
      array('id' => '35', 'district_id' => '4', 'name' => 'Kawkhali', 'name_bn' => 'কাউখালী', 'url' => 'kawkhali.rangamati.gov.bd'),
      array('id' => '36', 'district_id' => '4', 'name' => 'Baghaichari', 'name_bn' => 'বাঘাইছড়ি', 'url' => 'baghaichari.rangamati.gov.bd'),
      array('id' => '37', 'district_id' => '4', 'name' => 'Barkal', 'name_bn' => 'বরকল', 'url' => 'barkal.rangamati.gov.bd'),
      array('id' => '38', 'district_id' => '4', 'name' => 'Langadu', 'name_bn' => 'লংগদু', 'url' => 'langadu.rangamati.gov.bd'),
      array('id' => '39', 'district_id' => '4', 'name' => 'Rajasthali', 'name_bn' => 'রাজস্থলী', 'url' => 'rajasthali.rangamati.gov.bd'),
      array('id' => '40', 'district_id' => '4', 'name' => 'Belaichari', 'name_bn' => 'বিলাইছড়ি', 'url' => 'belaichari.rangamati.gov.bd'),
      array('id' => '41', 'district_id' => '4', 'name' => 'Juraichari', 'name_bn' => 'জুরাছড়ি', 'url' => 'juraichari.rangamati.gov.bd'),
      array('id' => '42', 'district_id' => '4', 'name' => 'Naniarchar', 'name_bn' => 'নানিয়ারচর', 'url' => 'naniarchar.rangamati.gov.bd'),
      array('id' => '43', 'district_id' => '5', 'name' => 'Noakhali Sadar', 'name_bn' => 'নোয়াখালী সদর', 'url' => 'sadar.noakhali.gov.bd'),
      array('id' => '44', 'district_id' => '5', 'name' => 'Companiganj', 'name_bn' => 'কোম্পানীগঞ্জ', 'url' => 'companiganj.noakhali.gov.bd'),
      array('id' => '45', 'district_id' => '5', 'name' => 'Begumganj', 'name_bn' => 'বেগমগঞ্জ', 'url' => 'begumganj.noakhali.gov.bd'),
      array('id' => '46', 'district_id' => '5', 'name' => 'Hatia', 'name_bn' => 'হাতিয়া', 'url' => 'hatia.noakhali.gov.bd'),
      array('id' => '47', 'district_id' => '5', 'name' => 'Subarnachar', 'name_bn' => 'সুবর্ণচর', 'url' => 'subarnachar.noakhali.gov.bd'),
      array('id' => '48', 'district_id' => '5', 'name' => 'Kabirhat', 'name_bn' => 'কবিরহাট', 'url' => 'kabirhat.noakhali.gov.bd'),
      array('id' => '49', 'district_id' => '5', 'name' => 'Senbug', 'name_bn' => 'সেনবাগ', 'url' => 'senbug.noakhali.gov.bd'),
      array('id' => '50', 'district_id' => '5', 'name' => 'Chatkhil', 'name_bn' => 'চাটখিল', 'url' => 'chatkhil.noakhali.gov.bd'),
      array('id' => '51', 'district_id' => '5', 'name' => 'Sonaimori', 'name_bn' => 'সোনাইমুড়ী', 'url' => 'sonaimori.noakhali.gov.bd'),
      array('id' => '52', 'district_id' => '6', 'name' => 'Haimchar', 'name_bn' => 'হাইমচর', 'url' => 'haimchar.chandpur.gov.bd'),
      array('id' => '53', 'district_id' => '6', 'name' => 'Kachua', 'name_bn' => 'কচুয়া', 'url' => 'kachua.chandpur.gov.bd'),
      array('id' => '54', 'district_id' => '6', 'name' => 'Shahrasti', 'name_bn' => 'শাহরাস্তি	', 'url' => 'shahrasti.chandpur.gov.bd'),
      array('id' => '55', 'district_id' => '6', 'name' => 'Chandpur Sadar', 'name_bn' => 'চাঁদপুর সদর', 'url' => 'sadar.chandpur.gov.bd'),
      array('id' => '56', 'district_id' => '6', 'name' => 'Matlab South', 'name_bn' => 'মতলব দক্ষিণ', 'url' => 'matlabsouth.chandpur.gov.bd'),
      array('id' => '57', 'district_id' => '6', 'name' => 'Hajiganj', 'name_bn' => 'হাজীগঞ্জ', 'url' => 'hajiganj.chandpur.gov.bd'),
      array('id' => '58', 'district_id' => '6', 'name' => 'Matlab North', 'name_bn' => 'মতলব উত্তর', 'url' => 'matlabnorth.chandpur.gov.bd'),
      array('id' => '59', 'district_id' => '6', 'name' => 'Faridgonj', 'name_bn' => 'ফরিদগঞ্জ', 'url' => 'faridgonj.chandpur.gov.bd'),
      array('id' => '60', 'district_id' => '7', 'name' => 'Lakshmipur Sadar', 'name_bn' => 'লক্ষ্মীপুর সদর', 'url' => 'sadar.lakshmipur.gov.bd'),
      array('id' => '61', 'district_id' => '7', 'name' => 'Kamalnagar', 'name_bn' => 'কমলনগর', 'url' => 'kamalnagar.lakshmipur.gov.bd'),
      array('id' => '62', 'district_id' => '7', 'name' => 'Raipur', 'name_bn' => 'রায়পুর', 'url' => 'raipur.lakshmipur.gov.bd'),
      array('id' => '63', 'district_id' => '7', 'name' => 'Ramgati', 'name_bn' => 'রামগতি', 'url' => 'ramgati.lakshmipur.gov.bd'),
      array('id' => '64', 'district_id' => '7', 'name' => 'Ramganj', 'name_bn' => 'রামগঞ্জ', 'url' => 'ramganj.lakshmipur.gov.bd'),
      array('id' => '65', 'district_id' => '8', 'name' => 'Rangunia', 'name_bn' => 'রাঙ্গুনিয়া', 'url' => 'rangunia.chittagong.gov.bd'),
      array('id' => '66', 'district_id' => '8', 'name' => 'Sitakunda', 'name_bn' => 'সীতাকুন্ড', 'url' => 'sitakunda.chittagong.gov.bd'),
      array('id' => '67', 'district_id' => '8', 'name' => 'Mirsharai', 'name_bn' => 'মীরসরাই', 'url' => 'mirsharai.chittagong.gov.bd'),
      array('id' => '68', 'district_id' => '8', 'name' => 'Patiya', 'name_bn' => 'পটিয়া', 'url' => 'patiya.chittagong.gov.bd'),
      array('id' => '69', 'district_id' => '8', 'name' => 'Sandwip', 'name_bn' => 'সন্দ্বীপ', 'url' => 'sandwip.chittagong.gov.bd'),
      array('id' => '70', 'district_id' => '8', 'name' => 'Banshkhali', 'name_bn' => 'বাঁশখালী', 'url' => 'banshkhali.chittagong.gov.bd'),
      array('id' => '71', 'district_id' => '8', 'name' => 'Boalkhali', 'name_bn' => 'বোয়ালখালী', 'url' => 'boalkhali.chittagong.gov.bd'),
      array('id' => '72', 'district_id' => '8', 'name' => 'Anwara', 'name_bn' => 'আনোয়ারা', 'url' => 'anwara.chittagong.gov.bd'),
      array('id' => '73', 'district_id' => '8', 'name' => 'Chandanaish', 'name_bn' => 'চন্দনাইশ', 'url' => 'chandanaish.chittagong.gov.bd'),
      array('id' => '74', 'district_id' => '8', 'name' => 'Satkania', 'name_bn' => 'সাতকানিয়া', 'url' => 'satkania.chittagong.gov.bd'),
      array('id' => '75', 'district_id' => '8', 'name' => 'Lohagara', 'name_bn' => 'লোহাগাড়া', 'url' => 'lohagara.chittagong.gov.bd'),
      array('id' => '76', 'district_id' => '8', 'name' => 'Hathazari', 'name_bn' => 'হাটহাজারী', 'url' => 'hathazari.chittagong.gov.bd'),
      array('id' => '77', 'district_id' => '8', 'name' => 'Fatikchhari', 'name_bn' => 'ফটিকছড়ি', 'url' => 'fatikchhari.chittagong.gov.bd'),
      array('id' => '78', 'district_id' => '8', 'name' => 'Raozan', 'name_bn' => 'রাউজান', 'url' => 'raozan.chittagong.gov.bd'),
      array('id' => '79', 'district_id' => '8', 'name' => 'Karnafuli', 'name_bn' => 'কর্ণফুলী', 'url' => 'karnafuli.chittagong.gov.bd'),
      array('id' => '80', 'district_id' => '9', 'name' => 'Coxsbazar Sadar', 'name_bn' => 'কক্সবাজার সদর', 'url' => 'sadar.coxsbazar.gov.bd'),
      array('id' => '81', 'district_id' => '9', 'name' => 'Chakaria', 'name_bn' => 'চকরিয়া', 'url' => 'chakaria.coxsbazar.gov.bd'),
      array('id' => '82', 'district_id' => '9', 'name' => 'Kutubdia', 'name_bn' => 'কুতুবদিয়া', 'url' => 'kutubdia.coxsbazar.gov.bd'),
      array('id' => '83', 'district_id' => '9', 'name' => 'Ukhiya', 'name_bn' => 'উখিয়া', 'url' => 'ukhiya.coxsbazar.gov.bd'),
      array('id' => '84', 'district_id' => '9', 'name' => 'Moheshkhali', 'name_bn' => 'মহেশখালী', 'url' => 'moheshkhali.coxsbazar.gov.bd'),
      array('id' => '85', 'district_id' => '9', 'name' => 'Pekua', 'name_bn' => 'পেকুয়া', 'url' => 'pekua.coxsbazar.gov.bd'),
      array('id' => '86', 'district_id' => '9', 'name' => 'Ramu', 'name_bn' => 'রামু', 'url' => 'ramu.coxsbazar.gov.bd'),
      array('id' => '87', 'district_id' => '9', 'name' => 'Teknaf', 'name_bn' => 'টেকনাফ', 'url' => 'teknaf.coxsbazar.gov.bd'),
      array('id' => '88', 'district_id' => '10', 'name' => 'Khagrachhari Sadar', 'name_bn' => 'খাগড়াছড়ি সদর', 'url' => 'sadar.khagrachhari.gov.bd'),
      array('id' => '89', 'district_id' => '10', 'name' => 'Dighinala', 'name_bn' => 'দিঘীনালা', 'url' => 'dighinala.khagrachhari.gov.bd'),
      array('id' => '90', 'district_id' => '10', 'name' => 'Panchari', 'name_bn' => 'পানছড়ি', 'url' => 'panchari.khagrachhari.gov.bd'),
      array('id' => '91', 'district_id' => '10', 'name' => 'Laxmichhari', 'name_bn' => 'লক্ষীছড়ি', 'url' => 'laxmichhari.khagrachhari.gov.bd'),
      array('id' => '92', 'district_id' => '10', 'name' => 'Mohalchari', 'name_bn' => 'মহালছড়ি', 'url' => 'mohalchari.khagrachhari.gov.bd'),
      array('id' => '93', 'district_id' => '10', 'name' => 'Manikchari', 'name_bn' => 'মানিকছড়ি', 'url' => 'manikchari.khagrachhari.gov.bd'),
      array('id' => '94', 'district_id' => '10', 'name' => 'Ramgarh', 'name_bn' => 'রামগড়', 'url' => 'ramgarh.khagrachhari.gov.bd'),
      array('id' => '95', 'district_id' => '10', 'name' => 'Matiranga', 'name_bn' => 'মাটিরাঙ্গা', 'url' => 'matiranga.khagrachhari.gov.bd'),
      array('id' => '96', 'district_id' => '10', 'name' => 'Guimara', 'name_bn' => 'গুইমারা', 'url' => 'guimara.khagrachhari.gov.bd'),
      array('id' => '97', 'district_id' => '11', 'name' => 'Bandarban Sadar', 'name_bn' => 'বান্দরবান সদর', 'url' => 'sadar.bandarban.gov.bd'),
      array('id' => '98', 'district_id' => '11', 'name' => 'Alikadam', 'name_bn' => 'আলীকদম', 'url' => 'alikadam.bandarban.gov.bd'),
      array('id' => '99', 'district_id' => '11', 'name' => 'Naikhongchhari', 'name_bn' => 'নাইক্ষ্যংছড়ি', 'url' => 'naikhongchhari.bandarban.gov.bd'),
      array('id' => '100', 'district_id' => '11', 'name' => 'Rowangchhari', 'name_bn' => 'রোয়াংছড়ি', 'url' => 'rowangchhari.bandarban.gov.bd'),
      array('id' => '101', 'district_id' => '11', 'name' => 'Lama', 'name_bn' => 'লামা', 'url' => 'lama.bandarban.gov.bd'),
      array('id' => '102', 'district_id' => '11', 'name' => 'Ruma', 'name_bn' => 'রুমা', 'url' => 'ruma.bandarban.gov.bd'),
      array('id' => '103', 'district_id' => '11', 'name' => 'Thanchi', 'name_bn' => 'থানচি', 'url' => 'thanchi.bandarban.gov.bd'),
      array('id' => '104', 'district_id' => '12', 'name' => 'Belkuchi', 'name_bn' => 'বেলকুচি', 'url' => 'belkuchi.sirajganj.gov.bd'),
      array('id' => '105', 'district_id' => '12', 'name' => 'Chauhali', 'name_bn' => 'চৌহালি', 'url' => 'chauhali.sirajganj.gov.bd'),
      array('id' => '106', 'district_id' => '12', 'name' => 'Kamarkhand', 'name_bn' => 'কামারখন্দ', 'url' => 'kamarkhand.sirajganj.gov.bd'),
      array('id' => '107', 'district_id' => '12', 'name' => 'Kazipur', 'name_bn' => 'কাজীপুর', 'url' => 'kazipur.sirajganj.gov.bd'),
      array('id' => '108', 'district_id' => '12', 'name' => 'Raigonj', 'name_bn' => 'রায়গঞ্জ', 'url' => 'raigonj.sirajganj.gov.bd'),
      array('id' => '109', 'district_id' => '12', 'name' => 'Shahjadpur', 'name_bn' => 'শাহজাদপুর', 'url' => 'shahjadpur.sirajganj.gov.bd'),
      array('id' => '110', 'district_id' => '12', 'name' => 'Sirajganj Sadar', 'name_bn' => 'সিরাজগঞ্জ সদর', 'url' => 'sirajganjsadar.sirajganj.gov.bd'),
      array('id' => '111', 'district_id' => '12', 'name' => 'Tarash', 'name_bn' => 'তাড়াশ', 'url' => 'tarash.sirajganj.gov.bd'),
      array('id' => '112', 'district_id' => '12', 'name' => 'Ullapara', 'name_bn' => 'উল্লাপাড়া', 'url' => 'ullapara.sirajganj.gov.bd'),
      array('id' => '113', 'district_id' => '13', 'name' => 'Sujanagar', 'name_bn' => 'সুজানগর', 'url' => 'sujanagar.pabna.gov.bd'),
      array('id' => '114', 'district_id' => '13', 'name' => 'Ishurdi', 'name_bn' => 'ঈশ্বরদী', 'url' => 'ishurdi.pabna.gov.bd'),
      array('id' => '115', 'district_id' => '13', 'name' => 'Bhangura', 'name_bn' => 'ভাঙ্গুড়া', 'url' => 'bhangura.pabna.gov.bd'),
      array('id' => '116', 'district_id' => '13', 'name' => 'Pabna Sadar', 'name_bn' => 'পাবনা সদর', 'url' => 'pabnasadar.pabna.gov.bd'),
      array('id' => '117', 'district_id' => '13', 'name' => 'Bera', 'name_bn' => 'বেড়া', 'url' => 'bera.pabna.gov.bd'),
      array('id' => '118', 'district_id' => '13', 'name' => 'Atghoria', 'name_bn' => 'আটঘরিয়া', 'url' => 'atghoria.pabna.gov.bd'),
      array('id' => '119', 'district_id' => '13', 'name' => 'Chatmohar', 'name_bn' => 'চাটমোহর', 'url' => 'chatmohar.pabna.gov.bd'),
      array('id' => '120', 'district_id' => '13', 'name' => 'Santhia', 'name_bn' => 'সাঁথিয়া', 'url' => 'santhia.pabna.gov.bd'),
      array('id' => '121', 'district_id' => '13', 'name' => 'Faridpur', 'name_bn' => 'ফরিদপুর', 'url' => 'faridpur.pabna.gov.bd'),
      array('id' => '122', 'district_id' => '14', 'name' => 'Kahaloo', 'name_bn' => 'কাহালু', 'url' => 'kahaloo.bogra.gov.bd'),
      array('id' => '123', 'district_id' => '14', 'name' => 'Bogra Sadar', 'name_bn' => 'বগুড়া সদর', 'url' => 'sadar.bogra.gov.bd'),
      array('id' => '124', 'district_id' => '14', 'name' => 'Shariakandi', 'name_bn' => 'সারিয়াকান্দি', 'url' => 'shariakandi.bogra.gov.bd'),
      array('id' => '125', 'district_id' => '14', 'name' => 'Shajahanpur', 'name_bn' => 'শাজাহানপুর', 'url' => 'shajahanpur.bogra.gov.bd'),
      array('id' => '126', 'district_id' => '14', 'name' => 'Dupchanchia', 'name_bn' => 'দুপচাচিঁয়া', 'url' => 'dupchanchia.bogra.gov.bd'),
      array('id' => '127', 'district_id' => '14', 'name' => 'Adamdighi', 'name_bn' => 'আদমদিঘি', 'url' => 'adamdighi.bogra.gov.bd'),
      array('id' => '128', 'district_id' => '14', 'name' => 'Nondigram', 'name_bn' => 'নন্দিগ্রাম', 'url' => 'nondigram.bogra.gov.bd'),
      array('id' => '129', 'district_id' => '14', 'name' => 'Sonatala', 'name_bn' => 'সোনাতলা', 'url' => 'sonatala.bogra.gov.bd'),
      array('id' => '130', 'district_id' => '14', 'name' => 'Dhunot', 'name_bn' => 'ধুনট', 'url' => 'dhunot.bogra.gov.bd'),
      array('id' => '131', 'district_id' => '14', 'name' => 'Gabtali', 'name_bn' => 'গাবতলী', 'url' => 'gabtali.bogra.gov.bd'),
      array('id' => '132', 'district_id' => '14', 'name' => 'Sherpur', 'name_bn' => 'শেরপুর', 'url' => 'sherpur.bogra.gov.bd'),
      array('id' => '133', 'district_id' => '14', 'name' => 'Shibganj', 'name_bn' => 'শিবগঞ্জ', 'url' => 'shibganj.bogra.gov.bd'),
      array('id' => '134', 'district_id' => '15', 'name' => 'Paba', 'name_bn' => 'পবা', 'url' => 'paba.rajshahi.gov.bd'),
      array('id' => '135', 'district_id' => '15', 'name' => 'Durgapur', 'name_bn' => 'দুর্গাপুর', 'url' => 'durgapur.rajshahi.gov.bd'),
      array('id' => '136', 'district_id' => '15', 'name' => 'Mohonpur', 'name_bn' => 'মোহনপুর', 'url' => 'mohonpur.rajshahi.gov.bd'),
      array('id' => '137', 'district_id' => '15', 'name' => 'Charghat', 'name_bn' => 'চারঘাট', 'url' => 'charghat.rajshahi.gov.bd'),
      array('id' => '138', 'district_id' => '15', 'name' => 'Puthia', 'name_bn' => 'পুঠিয়া', 'url' => 'puthia.rajshahi.gov.bd'),
      array('id' => '139', 'district_id' => '15', 'name' => 'Bagha', 'name_bn' => 'বাঘা', 'url' => 'bagha.rajshahi.gov.bd'),
      array('id' => '140', 'district_id' => '15', 'name' => 'Godagari', 'name_bn' => 'গোদাগাড়ী', 'url' => 'godagari.rajshahi.gov.bd'),
      array('id' => '141', 'district_id' => '15', 'name' => 'Tanore', 'name_bn' => 'তানোর', 'url' => 'tanore.rajshahi.gov.bd'),
      array('id' => '142', 'district_id' => '15', 'name' => 'Bagmara', 'name_bn' => 'বাগমারা', 'url' => 'bagmara.rajshahi.gov.bd'),
      array('id' => '143', 'district_id' => '16', 'name' => 'Natore Sadar', 'name_bn' => 'নাটোর সদর', 'url' => 'natoresadar.natore.gov.bd'),
      array('id' => '144', 'district_id' => '16', 'name' => 'Singra', 'name_bn' => 'সিংড়া', 'url' => 'singra.natore.gov.bd'),
      array('id' => '145', 'district_id' => '16', 'name' => 'Baraigram', 'name_bn' => 'বড়াইগ্রাম', 'url' => 'baraigram.natore.gov.bd'),
      array('id' => '146', 'district_id' => '16', 'name' => 'Bagatipara', 'name_bn' => 'বাগাতিপাড়া', 'url' => 'bagatipara.natore.gov.bd'),
      array('id' => '147', 'district_id' => '16', 'name' => 'Lalpur', 'name_bn' => 'লালপুর', 'url' => 'lalpur.natore.gov.bd'),
      array('id' => '148', 'district_id' => '16', 'name' => 'Gurudaspur', 'name_bn' => 'গুরুদাসপুর', 'url' => 'gurudaspur.natore.gov.bd'),
      array('id' => '149', 'district_id' => '16', 'name' => 'Naldanga', 'name_bn' => 'নলডাঙ্গা', 'url' => 'naldanga.natore.gov.bd'),
      array('id' => '150', 'district_id' => '17', 'name' => 'Akkelpur', 'name_bn' => 'আক্কেলপুর', 'url' => 'akkelpur.joypurhat.gov.bd'),
      array('id' => '151', 'district_id' => '17', 'name' => 'Kalai', 'name_bn' => 'কালাই', 'url' => 'kalai.joypurhat.gov.bd'),
      array('id' => '152', 'district_id' => '17', 'name' => 'Khetlal', 'name_bn' => 'ক্ষেতলাল', 'url' => 'khetlal.joypurhat.gov.bd'),
      array('id' => '153', 'district_id' => '17', 'name' => 'Panchbibi', 'name_bn' => 'পাঁচবিবি', 'url' => 'panchbibi.joypurhat.gov.bd'),
      array('id' => '154', 'district_id' => '17', 'name' => 'Joypurhat Sadar', 'name_bn' => 'জয়পুরহাট সদর', 'url' => 'joypurhatsadar.joypurhat.gov.bd'),
      array('id' => '155', 'district_id' => '18', 'name' => 'Chapainawabganj Sadar', 'name_bn' => 'চাঁপাইনবাবগঞ্জ সদর', 'url' => 'chapainawabganjsadar.chapainawabganj.gov.bd'),
      array('id' => '156', 'district_id' => '18', 'name' => 'Gomostapur', 'name_bn' => 'গোমস্তাপুর', 'url' => 'gomostapur.chapainawabganj.gov.bd'),
      array('id' => '157', 'district_id' => '18', 'name' => 'Nachol', 'name_bn' => 'নাচোল', 'url' => 'nachol.chapainawabganj.gov.bd'),
      array('id' => '158', 'district_id' => '18', 'name' => 'Bholahat', 'name_bn' => 'ভোলাহাট', 'url' => 'bholahat.chapainawabganj.gov.bd'),
      array('id' => '159', 'district_id' => '18', 'name' => 'Shibganj', 'name_bn' => 'শিবগঞ্জ', 'url' => 'shibganj.chapainawabganj.gov.bd'),
      array('id' => '160', 'district_id' => '19', 'name' => 'Mohadevpur', 'name_bn' => 'মহাদেবপুর', 'url' => 'mohadevpur.naogaon.gov.bd'),
      array('id' => '161', 'district_id' => '19', 'name' => 'Badalgachi', 'name_bn' => 'বদলগাছী', 'url' => 'badalgachi.naogaon.gov.bd'),
      array('id' => '162', 'district_id' => '19', 'name' => 'Patnitala', 'name_bn' => 'পত্নিতলা', 'url' => 'patnitala.naogaon.gov.bd'),
      array('id' => '163', 'district_id' => '19', 'name' => 'Dhamoirhat', 'name_bn' => 'ধামইরহাট', 'url' => 'dhamoirhat.naogaon.gov.bd'),
      array('id' => '164', 'district_id' => '19', 'name' => 'Niamatpur', 'name_bn' => 'নিয়ামতপুর', 'url' => 'niamatpur.naogaon.gov.bd'),
      array('id' => '165', 'district_id' => '19', 'name' => 'Manda', 'name_bn' => 'মান্দা', 'url' => 'manda.naogaon.gov.bd'),
      array('id' => '166', 'district_id' => '19', 'name' => 'Atrai', 'name_bn' => 'আত্রাই', 'url' => 'atrai.naogaon.gov.bd'),
      array('id' => '167', 'district_id' => '19', 'name' => 'Raninagar', 'name_bn' => 'রাণীনগর', 'url' => 'raninagar.naogaon.gov.bd'),
      array('id' => '168', 'district_id' => '19', 'name' => 'Naogaon Sadar', 'name_bn' => 'নওগাঁ সদর', 'url' => 'naogaonsadar.naogaon.gov.bd'),
      array('id' => '169', 'district_id' => '19', 'name' => 'Porsha', 'name_bn' => 'পোরশা', 'url' => 'porsha.naogaon.gov.bd'),
      array('id' => '170', 'district_id' => '19', 'name' => 'Sapahar', 'name_bn' => 'সাপাহার', 'url' => 'sapahar.naogaon.gov.bd'),
      array('id' => '171', 'district_id' => '20', 'name' => 'Manirampur', 'name_bn' => 'মণিরামপুর', 'url' => 'manirampur.jessore.gov.bd'),
      array('id' => '172', 'district_id' => '20', 'name' => 'Abhaynagar', 'name_bn' => 'অভয়নগর', 'url' => 'abhaynagar.jessore.gov.bd'),
      array('id' => '173', 'district_id' => '20', 'name' => 'Bagherpara', 'name_bn' => 'বাঘারপাড়া', 'url' => 'bagherpara.jessore.gov.bd'),
      array('id' => '174', 'district_id' => '20', 'name' => 'Chougachha', 'name_bn' => 'চৌগাছা', 'url' => 'chougachha.jessore.gov.bd'),
      array('id' => '175', 'district_id' => '20', 'name' => 'Jhikargacha', 'name_bn' => 'ঝিকরগাছা', 'url' => 'jhikargacha.jessore.gov.bd'),
      array('id' => '176', 'district_id' => '20', 'name' => 'Keshabpur', 'name_bn' => 'কেশবপুর', 'url' => 'keshabpur.jessore.gov.bd'),
      array('id' => '177', 'district_id' => '20', 'name' => 'Jessore Sadar', 'name_bn' => 'যশোর সদর', 'url' => 'sadar.jessore.gov.bd'),
      array('id' => '178', 'district_id' => '20', 'name' => 'Sharsha', 'name_bn' => 'শার্শা', 'url' => 'sharsha.jessore.gov.bd'),
      array('id' => '179', 'district_id' => '21', 'name' => 'Assasuni', 'name_bn' => 'আশাশুনি', 'url' => 'assasuni.satkhira.gov.bd'),
      array('id' => '180', 'district_id' => '21', 'name' => 'Debhata', 'name_bn' => 'দেবহাটা', 'url' => 'debhata.satkhira.gov.bd'),
      array('id' => '181', 'district_id' => '21', 'name' => 'Kalaroa', 'name_bn' => 'কলারোয়া', 'url' => 'kalaroa.satkhira.gov.bd'),
      array('id' => '182', 'district_id' => '21', 'name' => 'Satkhira Sadar', 'name_bn' => 'সাতক্ষীরা সদর', 'url' => 'satkhirasadar.satkhira.gov.bd'),
      array('id' => '183', 'district_id' => '21', 'name' => 'Shyamnagar', 'name_bn' => 'শ্যামনগর', 'url' => 'shyamnagar.satkhira.gov.bd'),
      array('id' => '184', 'district_id' => '21', 'name' => 'Tala', 'name_bn' => 'তালা', 'url' => 'tala.satkhira.gov.bd'),
      array('id' => '185', 'district_id' => '21', 'name' => 'Kaliganj', 'name_bn' => 'কালিগঞ্জ', 'url' => 'kaliganj.satkhira.gov.bd'),
      array('id' => '186', 'district_id' => '22', 'name' => 'Mujibnagar', 'name_bn' => 'মুজিবনগর', 'url' => 'mujibnagar.meherpur.gov.bd'),
      array('id' => '187', 'district_id' => '22', 'name' => 'Meherpur Sadar', 'name_bn' => 'মেহেরপুর সদর', 'url' => 'meherpursadar.meherpur.gov.bd'),
      array('id' => '188', 'district_id' => '22', 'name' => 'Gangni', 'name_bn' => 'গাংনী', 'url' => 'gangni.meherpur.gov.bd'),
      array('id' => '189', 'district_id' => '23', 'name' => 'Narail Sadar', 'name_bn' => 'নড়াইল সদর', 'url' => 'narailsadar.narail.gov.bd'),
      array('id' => '190', 'district_id' => '23', 'name' => 'Lohagara', 'name_bn' => 'লোহাগড়া', 'url' => 'lohagara.narail.gov.bd'),
      array('id' => '191', 'district_id' => '23', 'name' => 'Kalia', 'name_bn' => 'কালিয়া', 'url' => 'kalia.narail.gov.bd'),
      array('id' => '192', 'district_id' => '24', 'name' => 'Chuadanga Sadar', 'name_bn' => 'চুয়াডাঙ্গা সদর', 'url' => 'chuadangasadar.chuadanga.gov.bd'),
      array('id' => '193', 'district_id' => '24', 'name' => 'Alamdanga', 'name_bn' => 'আলমডাঙ্গা', 'url' => 'alamdanga.chuadanga.gov.bd'),
      array('id' => '194', 'district_id' => '24', 'name' => 'Damurhuda', 'name_bn' => 'দামুড়হুদা', 'url' => 'damurhuda.chuadanga.gov.bd'),
      array('id' => '195', 'district_id' => '24', 'name' => 'Jibannagar', 'name_bn' => 'জীবননগর', 'url' => 'jibannagar.chuadanga.gov.bd'),
      array('id' => '196', 'district_id' => '25', 'name' => 'Kushtia Sadar', 'name_bn' => 'কুষ্টিয়া সদর', 'url' => 'kushtiasadar.kushtia.gov.bd'),
      array('id' => '197', 'district_id' => '25', 'name' => 'Kumarkhali', 'name_bn' => 'কুমারখালী', 'url' => 'kumarkhali.kushtia.gov.bd'),
      array('id' => '198', 'district_id' => '25', 'name' => 'Khoksa', 'name_bn' => 'খোকসা', 'url' => 'khoksa.kushtia.gov.bd'),
      array('id' => '199', 'district_id' => '25', 'name' => 'Mirpur', 'name_bn' => 'মিরপুর', 'url' => 'mirpurkushtia.kushtia.gov.bd'),
      array('id' => '200', 'district_id' => '25', 'name' => 'Daulatpur', 'name_bn' => 'দৌলতপুর', 'url' => 'daulatpur.kushtia.gov.bd'),
      array('id' => '201', 'district_id' => '25', 'name' => 'Bheramara', 'name_bn' => 'ভেড়ামারা', 'url' => 'bheramara.kushtia.gov.bd'),
      array('id' => '202', 'district_id' => '26', 'name' => 'Shalikha', 'name_bn' => 'শালিখা', 'url' => 'shalikha.magura.gov.bd'),
      array('id' => '203', 'district_id' => '26', 'name' => 'Sreepur', 'name_bn' => 'শ্রীপুর', 'url' => 'sreepur.magura.gov.bd'),
      array('id' => '204', 'district_id' => '26', 'name' => 'Magura Sadar', 'name_bn' => 'মাগুরা সদর', 'url' => 'magurasadar.magura.gov.bd'),
      array('id' => '205', 'district_id' => '26', 'name' => 'Mohammadpur', 'name_bn' => 'মহম্মদপুর', 'url' => 'mohammadpur.magura.gov.bd'),
      array('id' => '206', 'district_id' => '27', 'name' => 'Paikgasa', 'name_bn' => 'পাইকগাছা', 'url' => 'paikgasa.khulna.gov.bd'),
      array('id' => '207', 'district_id' => '27', 'name' => 'Fultola', 'name_bn' => 'ফুলতলা', 'url' => 'fultola.khulna.gov.bd'),
      array('id' => '208', 'district_id' => '27', 'name' => 'Digholia', 'name_bn' => 'দিঘলিয়া', 'url' => 'digholia.khulna.gov.bd'),
      array('id' => '209', 'district_id' => '27', 'name' => 'Rupsha', 'name_bn' => 'রূপসা', 'url' => 'rupsha.khulna.gov.bd'),
      array('id' => '210', 'district_id' => '27', 'name' => 'Terokhada', 'name_bn' => 'তেরখাদা', 'url' => 'terokhada.khulna.gov.bd'),
      array('id' => '211', 'district_id' => '27', 'name' => 'Dumuria', 'name_bn' => 'ডুমুরিয়া', 'url' => 'dumuria.khulna.gov.bd'),
      array('id' => '212', 'district_id' => '27', 'name' => 'Botiaghata', 'name_bn' => 'বটিয়াঘাটা', 'url' => 'botiaghata.khulna.gov.bd'),
      array('id' => '213', 'district_id' => '27', 'name' => 'Dakop', 'name_bn' => 'দাকোপ', 'url' => 'dakop.khulna.gov.bd'),
      array('id' => '214', 'district_id' => '27', 'name' => 'Koyra', 'name_bn' => 'কয়রা', 'url' => 'koyra.khulna.gov.bd'),
      array('id' => '215', 'district_id' => '28', 'name' => 'Fakirhat', 'name_bn' => 'ফকিরহাট', 'url' => 'fakirhat.bagerhat.gov.bd'),
      array('id' => '216', 'district_id' => '28', 'name' => 'Bagerhat Sadar', 'name_bn' => 'বাগেরহাট সদর', 'url' => 'sadar.bagerhat.gov.bd'),
      array('id' => '217', 'district_id' => '28', 'name' => 'Mollahat', 'name_bn' => 'মোল্লাহাট', 'url' => 'mollahat.bagerhat.gov.bd'),
      array('id' => '218', 'district_id' => '28', 'name' => 'Sarankhola', 'name_bn' => 'শরণখোলা', 'url' => 'sarankhola.bagerhat.gov.bd'),
      array('id' => '219', 'district_id' => '28', 'name' => 'Rampal', 'name_bn' => 'রামপাল', 'url' => 'rampal.bagerhat.gov.bd'),
      array('id' => '220', 'district_id' => '28', 'name' => 'Morrelganj', 'name_bn' => 'মোড়েলগঞ্জ', 'url' => 'morrelganj.bagerhat.gov.bd'),
      array('id' => '221', 'district_id' => '28', 'name' => 'Kachua', 'name_bn' => 'কচুয়া', 'url' => 'kachua.bagerhat.gov.bd'),
      array('id' => '222', 'district_id' => '28', 'name' => 'Mongla', 'name_bn' => 'মোংলা', 'url' => 'mongla.bagerhat.gov.bd'),
      array('id' => '223', 'district_id' => '28', 'name' => 'Chitalmari', 'name_bn' => 'চিতলমারী', 'url' => 'chitalmari.bagerhat.gov.bd'),
      array('id' => '224', 'district_id' => '29', 'name' => 'Jhenaidah Sadar', 'name_bn' => 'ঝিনাইদহ সদর', 'url' => 'sadar.jhenaidah.gov.bd'),
      array('id' => '225', 'district_id' => '29', 'name' => 'Shailkupa', 'name_bn' => 'শৈলকুপা', 'url' => 'shailkupa.jhenaidah.gov.bd'),
      array('id' => '226', 'district_id' => '29', 'name' => 'Harinakundu', 'name_bn' => 'হরিণাকুন্ডু', 'url' => 'harinakundu.jhenaidah.gov.bd'),
      array('id' => '227', 'district_id' => '29', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.jhenaidah.gov.bd'),
      array('id' => '228', 'district_id' => '29', 'name' => 'Kotchandpur', 'name_bn' => 'কোটচাঁদপুর', 'url' => 'kotchandpur.jhenaidah.gov.bd'),
      array('id' => '229', 'district_id' => '29', 'name' => 'Moheshpur', 'name_bn' => 'মহেশপুর', 'url' => 'moheshpur.jhenaidah.gov.bd'),
      array('id' => '230', 'district_id' => '30', 'name' => 'Jhalakathi Sadar', 'name_bn' => 'ঝালকাঠি সদর', 'url' => 'sadar.jhalakathi.gov.bd'),
      array('id' => '231', 'district_id' => '30', 'name' => 'Kathalia', 'name_bn' => 'কাঠালিয়া', 'url' => 'kathalia.jhalakathi.gov.bd'),
      array('id' => '232', 'district_id' => '30', 'name' => 'Nalchity', 'name_bn' => 'নলছিটি', 'url' => 'nalchity.jhalakathi.gov.bd'),
      array('id' => '233', 'district_id' => '30', 'name' => 'Rajapur', 'name_bn' => 'রাজাপুর', 'url' => 'rajapur.jhalakathi.gov.bd'),
      array('id' => '234', 'district_id' => '31', 'name' => 'Bauphal', 'name_bn' => 'বাউফল', 'url' => 'bauphal.patuakhali.gov.bd'),
      array('id' => '235', 'district_id' => '31', 'name' => 'Patuakhali Sadar', 'name_bn' => 'পটুয়াখালী সদর', 'url' => 'sadar.patuakhali.gov.bd'),
      array('id' => '236', 'district_id' => '31', 'name' => 'Dumki', 'name_bn' => 'দুমকি', 'url' => 'dumki.patuakhali.gov.bd'),
      array('id' => '237', 'district_id' => '31', 'name' => 'Dashmina', 'name_bn' => 'দশমিনা', 'url' => 'dashmina.patuakhali.gov.bd'),
      array('id' => '238', 'district_id' => '31', 'name' => 'Kalapara', 'name_bn' => 'কলাপাড়া', 'url' => 'kalapara.patuakhali.gov.bd'),
      array('id' => '239', 'district_id' => '31', 'name' => 'Mirzaganj', 'name_bn' => 'মির্জাগঞ্জ', 'url' => 'mirzaganj.patuakhali.gov.bd'),
      array('id' => '240', 'district_id' => '31', 'name' => 'Galachipa', 'name_bn' => 'গলাচিপা', 'url' => 'galachipa.patuakhali.gov.bd'),
      array('id' => '241', 'district_id' => '31', 'name' => 'Rangabali', 'name_bn' => 'রাঙ্গাবালী', 'url' => 'rangabali.patuakhali.gov.bd'),
      array('id' => '242', 'district_id' => '32', 'name' => 'Pirojpur Sadar', 'name_bn' => 'পিরোজপুর সদর', 'url' => 'sadar.pirojpur.gov.bd'),
      array('id' => '243', 'district_id' => '32', 'name' => 'Nazirpur', 'name_bn' => 'নাজিরপুর', 'url' => 'nazirpur.pirojpur.gov.bd'),
      array('id' => '244', 'district_id' => '32', 'name' => 'Kawkhali', 'name_bn' => 'কাউখালী', 'url' => 'kawkhali.pirojpur.gov.bd'),
      array('id' => '245', 'district_id' => '32', 'name' => 'Zianagar', 'name_bn' => 'জিয়ানগর', 'url' => 'zianagar.pirojpur.gov.bd'),
      array('id' => '246', 'district_id' => '32', 'name' => 'Bhandaria', 'name_bn' => 'ভান্ডারিয়া', 'url' => 'bhandaria.pirojpur.gov.bd'),
      array('id' => '247', 'district_id' => '32', 'name' => 'Mathbaria', 'name_bn' => 'মঠবাড়ীয়া', 'url' => 'mathbaria.pirojpur.gov.bd'),
      array('id' => '248', 'district_id' => '32', 'name' => 'Nesarabad', 'name_bn' => 'নেছারাবাদ', 'url' => 'nesarabad.pirojpur.gov.bd'),
      array('id' => '249', 'district_id' => '33', 'name' => 'Barisal Sadar', 'name_bn' => 'বরিশাল সদর', 'url' => 'barisalsadar.barisal.gov.bd'),
      array('id' => '250', 'district_id' => '33', 'name' => 'Bakerganj', 'name_bn' => 'বাকেরগঞ্জ', 'url' => 'bakerganj.barisal.gov.bd'),
      array('id' => '251', 'district_id' => '33', 'name' => 'Babuganj', 'name_bn' => 'বাবুগঞ্জ', 'url' => 'babuganj.barisal.gov.bd'),
      array('id' => '252', 'district_id' => '33', 'name' => 'Wazirpur', 'name_bn' => 'উজিরপুর', 'url' => 'wazirpur.barisal.gov.bd'),
      array('id' => '253', 'district_id' => '33', 'name' => 'Banaripara', 'name_bn' => 'বানারীপাড়া', 'url' => 'banaripara.barisal.gov.bd'),
      array('id' => '254', 'district_id' => '33', 'name' => 'Gournadi', 'name_bn' => 'গৌরনদী', 'url' => 'gournadi.barisal.gov.bd'),
      array('id' => '255', 'district_id' => '33', 'name' => 'Agailjhara', 'name_bn' => 'আগৈলঝাড়া', 'url' => 'agailjhara.barisal.gov.bd'),
      array('id' => '256', 'district_id' => '33', 'name' => 'Mehendiganj', 'name_bn' => 'মেহেন্দিগঞ্জ', 'url' => 'mehendiganj.barisal.gov.bd'),
      array('id' => '257', 'district_id' => '33', 'name' => 'Muladi', 'name_bn' => 'মুলাদী', 'url' => 'muladi.barisal.gov.bd'),
      array('id' => '258', 'district_id' => '33', 'name' => 'Hizla', 'name_bn' => 'হিজলা', 'url' => 'hizla.barisal.gov.bd'),
      array('id' => '259', 'district_id' => '34', 'name' => 'Bhola Sadar', 'name_bn' => 'ভোলা সদর', 'url' => 'sadar.bhola.gov.bd'),
      array('id' => '260', 'district_id' => '34', 'name' => 'Borhan Sddin', 'name_bn' => 'বোরহান উদ্দিন', 'url' => 'borhanuddin.bhola.gov.bd'),
      array('id' => '261', 'district_id' => '34', 'name' => 'Charfesson', 'name_bn' => 'চরফ্যাশন', 'url' => 'charfesson.bhola.gov.bd'),
      array('id' => '262', 'district_id' => '34', 'name' => 'Doulatkhan', 'name_bn' => 'দৌলতখান', 'url' => 'doulatkhan.bhola.gov.bd'),
      array('id' => '263', 'district_id' => '34', 'name' => 'Monpura', 'name_bn' => 'মনপুরা', 'url' => 'monpura.bhola.gov.bd'),
      array('id' => '264', 'district_id' => '34', 'name' => 'Tazumuddin', 'name_bn' => 'তজুমদ্দিন', 'url' => 'tazumuddin.bhola.gov.bd'),
      array('id' => '265', 'district_id' => '34', 'name' => 'Lalmohan', 'name_bn' => 'লালমোহন', 'url' => 'lalmohan.bhola.gov.bd'),
      array('id' => '266', 'district_id' => '35', 'name' => 'Amtali', 'name_bn' => 'আমতলী', 'url' => 'amtali.barguna.gov.bd'),
      array('id' => '267', 'district_id' => '35', 'name' => 'Barguna Sadar', 'name_bn' => 'বরগুনা সদর', 'url' => 'sadar.barguna.gov.bd'),
      array('id' => '268', 'district_id' => '35', 'name' => 'Betagi', 'name_bn' => 'বেতাগী', 'url' => 'betagi.barguna.gov.bd'),
      array('id' => '269', 'district_id' => '35', 'name' => 'Bamna', 'name_bn' => 'বামনা', 'url' => 'bamna.barguna.gov.bd'),
      array('id' => '270', 'district_id' => '35', 'name' => 'Pathorghata', 'name_bn' => 'পাথরঘাটা', 'url' => 'pathorghata.barguna.gov.bd'),
      array('id' => '271', 'district_id' => '35', 'name' => 'Taltali', 'name_bn' => 'তালতলি', 'url' => 'taltali.barguna.gov.bd'),
      array('id' => '272', 'district_id' => '36', 'name' => 'Balaganj', 'name_bn' => 'বালাগঞ্জ', 'url' => 'balaganj.sylhet.gov.bd'),
      array('id' => '273', 'district_id' => '36', 'name' => 'Beanibazar', 'name_bn' => 'বিয়ানীবাজার', 'url' => 'beanibazar.sylhet.gov.bd'),
      array('id' => '274', 'district_id' => '36', 'name' => 'Bishwanath', 'name_bn' => 'বিশ্বনাথ', 'url' => 'bishwanath.sylhet.gov.bd'),
      array('id' => '275', 'district_id' => '36', 'name' => 'Companiganj', 'name_bn' => 'কোম্পানীগঞ্জ', 'url' => 'companiganj.sylhet.gov.bd'),
      array('id' => '276', 'district_id' => '36', 'name' => 'Fenchuganj', 'name_bn' => 'ফেঞ্চুগঞ্জ', 'url' => 'fenchuganj.sylhet.gov.bd'),
      array('id' => '277', 'district_id' => '36', 'name' => 'Golapganj', 'name_bn' => 'গোলাপগঞ্জ', 'url' => 'golapganj.sylhet.gov.bd'),
      array('id' => '278', 'district_id' => '36', 'name' => 'Gowainghat', 'name_bn' => 'গোয়াইনঘাট', 'url' => 'gowainghat.sylhet.gov.bd'),
      array('id' => '279', 'district_id' => '36', 'name' => 'Jaintiapur', 'name_bn' => 'জৈন্তাপুর', 'url' => 'jaintiapur.sylhet.gov.bd'),
      array('id' => '280', 'district_id' => '36', 'name' => 'Kanaighat', 'name_bn' => 'কানাইঘাট', 'url' => 'kanaighat.sylhet.gov.bd'),
      array('id' => '281', 'district_id' => '36', 'name' => 'Sylhet Sadar', 'name_bn' => 'সিলেট সদর', 'url' => 'sylhetsadar.sylhet.gov.bd'),
      array('id' => '282', 'district_id' => '36', 'name' => 'Zakiganj', 'name_bn' => 'জকিগঞ্জ', 'url' => 'zakiganj.sylhet.gov.bd'),
      array('id' => '283', 'district_id' => '36', 'name' => 'Dakshinsurma', 'name_bn' => 'দক্ষিণ সুরমা', 'url' => 'dakshinsurma.sylhet.gov.bd'),
      array('id' => '284', 'district_id' => '36', 'name' => 'Osmaninagar', 'name_bn' => 'ওসমানী নগর', 'url' => 'osmaninagar.sylhet.gov.bd'),
      array('id' => '285', 'district_id' => '37', 'name' => 'Barlekha', 'name_bn' => 'বড়লেখা', 'url' => 'barlekha.moulvibazar.gov.bd'),
      array('id' => '286', 'district_id' => '37', 'name' => 'Kamolganj', 'name_bn' => 'কমলগঞ্জ', 'url' => 'kamolganj.moulvibazar.gov.bd'),
      array('id' => '287', 'district_id' => '37', 'name' => 'Kulaura', 'name_bn' => 'কুলাউড়া', 'url' => 'kulaura.moulvibazar.gov.bd'),
      array('id' => '288', 'district_id' => '37', 'name' => 'Moulvibazar Sadar', 'name_bn' => 'মৌলভীবাজার সদর', 'url' => 'moulvibazarsadar.moulvibazar.gov.bd'),
      array('id' => '289', 'district_id' => '37', 'name' => 'Rajnagar', 'name_bn' => 'রাজনগর', 'url' => 'rajnagar.moulvibazar.gov.bd'),
      array('id' => '290', 'district_id' => '37', 'name' => 'Sreemangal', 'name_bn' => 'শ্রীমঙ্গল', 'url' => 'sreemangal.moulvibazar.gov.bd'),
      array('id' => '291', 'district_id' => '37', 'name' => 'Juri', 'name_bn' => 'জুড়ী', 'url' => 'juri.moulvibazar.gov.bd'),
      array('id' => '292', 'district_id' => '38', 'name' => 'Nabiganj', 'name_bn' => 'নবীগঞ্জ', 'url' => 'nabiganj.habiganj.gov.bd'),
      array('id' => '293', 'district_id' => '38', 'name' => 'Bahubal', 'name_bn' => 'বাহুবল', 'url' => 'bahubal.habiganj.gov.bd'),
      array('id' => '294', 'district_id' => '38', 'name' => 'Ajmiriganj', 'name_bn' => 'আজমিরীগঞ্জ', 'url' => 'ajmiriganj.habiganj.gov.bd'),
      array('id' => '295', 'district_id' => '38', 'name' => 'Baniachong', 'name_bn' => 'বানিয়াচং', 'url' => 'baniachong.habiganj.gov.bd'),
      array('id' => '296', 'district_id' => '38', 'name' => 'Lakhai', 'name_bn' => 'লাখাই', 'url' => 'lakhai.habiganj.gov.bd'),
      array('id' => '297', 'district_id' => '38', 'name' => 'Chunarughat', 'name_bn' => 'চুনারুঘাট', 'url' => 'chunarughat.habiganj.gov.bd'),
      array('id' => '298', 'district_id' => '38', 'name' => 'Habiganj Sadar', 'name_bn' => 'হবিগঞ্জ সদর', 'url' => 'habiganjsadar.habiganj.gov.bd'),
      array('id' => '299', 'district_id' => '38', 'name' => 'Madhabpur', 'name_bn' => 'মাধবপুর', 'url' => 'madhabpur.habiganj.gov.bd'),
      array('id' => '300', 'district_id' => '39', 'name' => 'Sunamganj Sadar', 'name_bn' => 'সুনামগঞ্জ সদর', 'url' => 'sadar.sunamganj.gov.bd'),
      array('id' => '301', 'district_id' => '39', 'name' => 'South Sunamganj', 'name_bn' => 'দক্ষিণ সুনামগঞ্জ', 'url' => 'southsunamganj.sunamganj.gov.bd'),
      array('id' => '302', 'district_id' => '39', 'name' => 'Bishwambarpur', 'name_bn' => 'বিশ্বম্ভরপুর', 'url' => 'bishwambarpur.sunamganj.gov.bd'),
      array('id' => '303', 'district_id' => '39', 'name' => 'Chhatak', 'name_bn' => 'ছাতক', 'url' => 'chhatak.sunamganj.gov.bd'),
      array('id' => '304', 'district_id' => '39', 'name' => 'Jagannathpur', 'name_bn' => 'জগন্নাথপুর', 'url' => 'jagannathpur.sunamganj.gov.bd'),
      array('id' => '305', 'district_id' => '39', 'name' => 'Dowarabazar', 'name_bn' => 'দোয়ারাবাজার', 'url' => 'dowarabazar.sunamganj.gov.bd'),
      array('id' => '306', 'district_id' => '39', 'name' => 'Tahirpur', 'name_bn' => 'তাহিরপুর', 'url' => 'tahirpur.sunamganj.gov.bd'),
      array('id' => '307', 'district_id' => '39', 'name' => 'Dharmapasha', 'name_bn' => 'ধর্মপাশা', 'url' => 'dharmapasha.sunamganj.gov.bd'),
      array('id' => '308', 'district_id' => '39', 'name' => 'Jamalganj', 'name_bn' => 'জামালগঞ্জ', 'url' => 'jamalganj.sunamganj.gov.bd'),
      array('id' => '309', 'district_id' => '39', 'name' => 'Shalla', 'name_bn' => 'শাল্লা', 'url' => 'shalla.sunamganj.gov.bd'),
      array('id' => '310', 'district_id' => '39', 'name' => 'Derai', 'name_bn' => 'দিরাই', 'url' => 'derai.sunamganj.gov.bd'),
      array('id' => '311', 'district_id' => '40', 'name' => 'Belabo', 'name_bn' => 'বেলাবো', 'url' => 'belabo.narsingdi.gov.bd'),
      array('id' => '312', 'district_id' => '40', 'name' => 'Monohardi', 'name_bn' => 'মনোহরদী', 'url' => 'monohardi.narsingdi.gov.bd'),
      array('id' => '313', 'district_id' => '40', 'name' => 'Narsingdi Sadar', 'name_bn' => 'নরসিংদী সদর', 'url' => 'narsingdisadar.narsingdi.gov.bd'),
      array('id' => '314', 'district_id' => '40', 'name' => 'Palash', 'name_bn' => 'পলাশ', 'url' => 'palash.narsingdi.gov.bd'),
      array('id' => '315', 'district_id' => '40', 'name' => 'Raipura', 'name_bn' => 'রায়পুরা', 'url' => 'raipura.narsingdi.gov.bd'),
      array('id' => '316', 'district_id' => '40', 'name' => 'Shibpur', 'name_bn' => 'শিবপুর', 'url' => 'shibpur.narsingdi.gov.bd'),
      array('id' => '317', 'district_id' => '41', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.gazipur.gov.bd'),
      array('id' => '318', 'district_id' => '41', 'name' => 'Kaliakair', 'name_bn' => 'কালিয়াকৈর', 'url' => 'kaliakair.gazipur.gov.bd'),
      array('id' => '319', 'district_id' => '41', 'name' => 'Kapasia', 'name_bn' => 'কাপাসিয়া', 'url' => 'kapasia.gazipur.gov.bd'),
      array('id' => '320', 'district_id' => '41', 'name' => 'Gazipur Sadar', 'name_bn' => 'গাজীপুর সদর', 'url' => 'sadar.gazipur.gov.bd'),
      array('id' => '321', 'district_id' => '41', 'name' => 'Sreepur', 'name_bn' => 'শ্রীপুর', 'url' => 'sreepur.gazipur.gov.bd'),
      array('id' => '322', 'district_id' => '42', 'name' => 'Shariatpur Sadar', 'name_bn' => 'শরিয়তপুর সদর', 'url' => 'sadar.shariatpur.gov.bd'),
      array('id' => '323', 'district_id' => '42', 'name' => 'Naria', 'name_bn' => 'নড়িয়া', 'url' => 'naria.shariatpur.gov.bd'),
      array('id' => '324', 'district_id' => '42', 'name' => 'Zajira', 'name_bn' => 'জাজিরা', 'url' => 'zajira.shariatpur.gov.bd'),
      array('id' => '325', 'district_id' => '42', 'name' => 'Gosairhat', 'name_bn' => 'গোসাইরহাট', 'url' => 'gosairhat.shariatpur.gov.bd'),
      array('id' => '326', 'district_id' => '42', 'name' => 'Bhedarganj', 'name_bn' => 'ভেদরগঞ্জ', 'url' => 'bhedarganj.shariatpur.gov.bd'),
      array('id' => '327', 'district_id' => '42', 'name' => 'Damudya', 'name_bn' => 'ডামুড্যা', 'url' => 'damudya.shariatpur.gov.bd'),
      array('id' => '328', 'district_id' => '43', 'name' => 'Araihazar', 'name_bn' => 'আড়াইহাজার', 'url' => 'araihazar.narayanganj.gov.bd'),
      array('id' => '329', 'district_id' => '43', 'name' => 'Bandar', 'name_bn' => 'বন্দর', 'url' => 'bandar.narayanganj.gov.bd'),
      array('id' => '330', 'district_id' => '43', 'name' => 'Narayanganj Sadar', 'name_bn' => 'নারায়নগঞ্জ সদর', 'url' => 'narayanganjsadar.narayanganj.gov.bd'),
      array('id' => '331', 'district_id' => '43', 'name' => 'Rupganj', 'name_bn' => 'রূপগঞ্জ', 'url' => 'rupganj.narayanganj.gov.bd'),
      array('id' => '332', 'district_id' => '43', 'name' => 'Sonargaon', 'name_bn' => 'সোনারগাঁ', 'url' => 'sonargaon.narayanganj.gov.bd'),
      array('id' => '333', 'district_id' => '44', 'name' => 'Basail', 'name_bn' => 'বাসাইল', 'url' => 'basail.tangail.gov.bd'),
      array('id' => '334', 'district_id' => '44', 'name' => 'Bhuapur', 'name_bn' => 'ভুয়াপুর', 'url' => 'bhuapur.tangail.gov.bd'),
      array('id' => '335', 'district_id' => '44', 'name' => 'Delduar', 'name_bn' => 'দেলদুয়ার', 'url' => 'delduar.tangail.gov.bd'),
      array('id' => '336', 'district_id' => '44', 'name' => 'Ghatail', 'name_bn' => 'ঘাটাইল', 'url' => 'ghatail.tangail.gov.bd'),
      array('id' => '337', 'district_id' => '44', 'name' => 'Gopalpur', 'name_bn' => 'গোপালপুর', 'url' => 'gopalpur.tangail.gov.bd'),
      array('id' => '338', 'district_id' => '44', 'name' => 'Madhupur', 'name_bn' => 'মধুপুর', 'url' => 'madhupur.tangail.gov.bd'),
      array('id' => '339', 'district_id' => '44', 'name' => 'Mirzapur', 'name_bn' => 'মির্জাপুর', 'url' => 'mirzapur.tangail.gov.bd'),
      array('id' => '340', 'district_id' => '44', 'name' => 'Nagarpur', 'name_bn' => 'নাগরপুর', 'url' => 'nagarpur.tangail.gov.bd'),
      array('id' => '341', 'district_id' => '44', 'name' => 'Sakhipur', 'name_bn' => 'সখিপুর', 'url' => 'sakhipur.tangail.gov.bd'),
      array('id' => '342', 'district_id' => '44', 'name' => 'Tangail Sadar', 'name_bn' => 'টাঙ্গাইল সদর', 'url' => 'tangailsadar.tangail.gov.bd'),
      array('id' => '343', 'district_id' => '44', 'name' => 'Kalihati', 'name_bn' => 'কালিহাতী', 'url' => 'kalihati.tangail.gov.bd'),
      array('id' => '344', 'district_id' => '44', 'name' => 'Dhanbari', 'name_bn' => 'ধনবাড়ী', 'url' => 'dhanbari.tangail.gov.bd'),
      array('id' => '345', 'district_id' => '45', 'name' => 'Itna', 'name_bn' => 'ইটনা', 'url' => 'itna.kishoreganj.gov.bd'),
      array('id' => '346', 'district_id' => '45', 'name' => 'Katiadi', 'name_bn' => 'কটিয়াদী', 'url' => 'katiadi.kishoreganj.gov.bd'),
      array('id' => '347', 'district_id' => '45', 'name' => 'Bhairab', 'name_bn' => 'ভৈরব', 'url' => 'bhairab.kishoreganj.gov.bd'),
      array('id' => '348', 'district_id' => '45', 'name' => 'Tarail', 'name_bn' => 'তাড়াইল', 'url' => 'tarail.kishoreganj.gov.bd'),
      array('id' => '349', 'district_id' => '45', 'name' => 'Hossainpur', 'name_bn' => 'হোসেনপুর', 'url' => 'hossainpur.kishoreganj.gov.bd'),
      array('id' => '350', 'district_id' => '45', 'name' => 'Pakundia', 'name_bn' => 'পাকুন্দিয়া', 'url' => 'pakundia.kishoreganj.gov.bd'),
      array('id' => '351', 'district_id' => '45', 'name' => 'Kuliarchar', 'name_bn' => 'কুলিয়ারচর', 'url' => 'kuliarchar.kishoreganj.gov.bd'),
      array('id' => '352', 'district_id' => '45', 'name' => 'Kishoreganj Sadar', 'name_bn' => 'কিশোরগঞ্জ সদর', 'url' => 'kishoreganjsadar.kishoreganj.gov.bd'),
      array('id' => '353', 'district_id' => '45', 'name' => 'Karimgonj', 'name_bn' => 'করিমগঞ্জ', 'url' => 'karimgonj.kishoreganj.gov.bd'),
      array('id' => '354', 'district_id' => '45', 'name' => 'Bajitpur', 'name_bn' => 'বাজিতপুর', 'url' => 'bajitpur.kishoreganj.gov.bd'),
      array('id' => '355', 'district_id' => '45', 'name' => 'Austagram', 'name_bn' => 'অষ্টগ্রাম', 'url' => 'austagram.kishoreganj.gov.bd'),
      array('id' => '356', 'district_id' => '45', 'name' => 'Mithamoin', 'name_bn' => 'মিঠামইন', 'url' => 'mithamoin.kishoreganj.gov.bd'),
      array('id' => '357', 'district_id' => '45', 'name' => 'Nikli', 'name_bn' => 'নিকলী', 'url' => 'nikli.kishoreganj.gov.bd'),
      array('id' => '358', 'district_id' => '46', 'name' => 'Harirampur', 'name_bn' => 'হরিরামপুর', 'url' => 'harirampur.manikganj.gov.bd'),
      array('id' => '359', 'district_id' => '46', 'name' => 'Saturia', 'name_bn' => 'সাটুরিয়া', 'url' => 'saturia.manikganj.gov.bd'),
      array('id' => '360', 'district_id' => '46', 'name' => 'Manikganj Sadar', 'name_bn' => 'মানিকগঞ্জ সদর', 'url' => 'sadar.manikganj.gov.bd'),
      array('id' => '361', 'district_id' => '46', 'name' => 'Gior', 'name_bn' => 'ঘিওর', 'url' => 'gior.manikganj.gov.bd'),
      array('id' => '362', 'district_id' => '46', 'name' => 'Shibaloy', 'name_bn' => 'শিবালয়', 'url' => 'shibaloy.manikganj.gov.bd'),
      array('id' => '363', 'district_id' => '46', 'name' => 'Doulatpur', 'name_bn' => 'দৌলতপুর', 'url' => 'doulatpur.manikganj.gov.bd'),
      array('id' => '364', 'district_id' => '46', 'name' => 'Singiar', 'name_bn' => 'সিংগাইর', 'url' => 'singiar.manikganj.gov.bd'),
      array('id' => '365', 'district_id' => '47', 'name' => 'Savar', 'name_bn' => 'সাভার', 'url' => 'savar.dhaka.gov.bd'),
      array('id' => '366', 'district_id' => '47', 'name' => 'Dhamrai', 'name_bn' => 'ধামরাই', 'url' => 'dhamrai.dhaka.gov.bd'),
      array('id' => '367', 'district_id' => '47', 'name' => 'Keraniganj', 'name_bn' => 'কেরাণীগঞ্জ', 'url' => 'keraniganj.dhaka.gov.bd'),
      array('id' => '368', 'district_id' => '47', 'name' => 'Nawabganj', 'name_bn' => 'নবাবগঞ্জ', 'url' => 'nawabganj.dhaka.gov.bd'),
      array('id' => '369', 'district_id' => '47', 'name' => 'Dohar', 'name_bn' => 'দোহার', 'url' => 'dohar.dhaka.gov.bd'),
      array('id' => '370', 'district_id' => '48', 'name' => 'Munshiganj Sadar', 'name_bn' => 'মুন্সিগঞ্জ সদর', 'url' => 'sadar.munshiganj.gov.bd'),
      array('id' => '371', 'district_id' => '48', 'name' => 'Sreenagar', 'name_bn' => 'শ্রীনগর', 'url' => 'sreenagar.munshiganj.gov.bd'),
      array('id' => '372', 'district_id' => '48', 'name' => 'Sirajdikhan', 'name_bn' => 'সিরাজদিখান', 'url' => 'sirajdikhan.munshiganj.gov.bd'),
      array('id' => '373', 'district_id' => '48', 'name' => 'Louhajanj', 'name_bn' => 'লৌহজং', 'url' => 'louhajanj.munshiganj.gov.bd'),
      array('id' => '374', 'district_id' => '48', 'name' => 'Gajaria', 'name_bn' => 'গজারিয়া', 'url' => 'gajaria.munshiganj.gov.bd'),
      array('id' => '375', 'district_id' => '48', 'name' => 'Tongibari', 'name_bn' => 'টংগীবাড়ি', 'url' => 'tongibari.munshiganj.gov.bd'),
      array('id' => '376', 'district_id' => '49', 'name' => 'Rajbari Sadar', 'name_bn' => 'রাজবাড়ী সদর', 'url' => 'sadar.rajbari.gov.bd'),
      array('id' => '377', 'district_id' => '49', 'name' => 'Goalanda', 'name_bn' => 'গোয়ালন্দ', 'url' => 'goalanda.rajbari.gov.bd'),
      array('id' => '378', 'district_id' => '49', 'name' => 'Pangsa', 'name_bn' => 'পাংশা', 'url' => 'pangsa.rajbari.gov.bd'),
      array('id' => '379', 'district_id' => '49', 'name' => 'Baliakandi', 'name_bn' => 'বালিয়াকান্দি', 'url' => 'baliakandi.rajbari.gov.bd'),
      array('id' => '380', 'district_id' => '49', 'name' => 'Kalukhali', 'name_bn' => 'কালুখালী', 'url' => 'kalukhali.rajbari.gov.bd'),
      array('id' => '381', 'district_id' => '50', 'name' => 'Madaripur Sadar', 'name_bn' => 'মাদারীপুর সদর', 'url' => 'sadar.madaripur.gov.bd'),
      array('id' => '382', 'district_id' => '50', 'name' => 'Shibchar', 'name_bn' => 'শিবচর', 'url' => 'shibchar.madaripur.gov.bd'),
      array('id' => '383', 'district_id' => '50', 'name' => 'Kalkini', 'name_bn' => 'কালকিনি', 'url' => 'kalkini.madaripur.gov.bd'),
      array('id' => '384', 'district_id' => '50', 'name' => 'Rajoir', 'name_bn' => 'রাজৈর', 'url' => 'rajoir.madaripur.gov.bd'),
      array('id' => '385', 'district_id' => '51', 'name' => 'Gopalganj Sadar', 'name_bn' => 'গোপালগঞ্জ সদর', 'url' => 'sadar.gopalganj.gov.bd'),
      array('id' => '386', 'district_id' => '51', 'name' => 'Kashiani', 'name_bn' => 'কাশিয়ানী', 'url' => 'kashiani.gopalganj.gov.bd'),
      array('id' => '387', 'district_id' => '51', 'name' => 'Tungipara', 'name_bn' => 'টুংগীপাড়া', 'url' => 'tungipara.gopalganj.gov.bd'),
      array('id' => '388', 'district_id' => '51', 'name' => 'Kotalipara', 'name_bn' => 'কোটালীপাড়া', 'url' => 'kotalipara.gopalganj.gov.bd'),
      array('id' => '389', 'district_id' => '51', 'name' => 'Muksudpur', 'name_bn' => 'মুকসুদপুর', 'url' => 'muksudpur.gopalganj.gov.bd'),
      array('id' => '390', 'district_id' => '52', 'name' => 'Faridpur Sadar', 'name_bn' => 'ফরিদপুর সদর', 'url' => 'sadar.faridpur.gov.bd'),
      array('id' => '391', 'district_id' => '52', 'name' => 'Alfadanga', 'name_bn' => 'আলফাডাঙ্গা', 'url' => 'alfadanga.faridpur.gov.bd'),
      array('id' => '392', 'district_id' => '52', 'name' => 'Boalmari', 'name_bn' => 'বোয়ালমারী', 'url' => 'boalmari.faridpur.gov.bd'),
      array('id' => '393', 'district_id' => '52', 'name' => 'Sadarpur', 'name_bn' => 'সদরপুর', 'url' => 'sadarpur.faridpur.gov.bd'),
      array('id' => '394', 'district_id' => '52', 'name' => 'Nagarkanda', 'name_bn' => 'নগরকান্দা', 'url' => 'nagarkanda.faridpur.gov.bd'),
      array('id' => '395', 'district_id' => '52', 'name' => 'Bhanga', 'name_bn' => 'ভাঙ্গা', 'url' => 'bhanga.faridpur.gov.bd'),
      array('id' => '396', 'district_id' => '52', 'name' => 'Charbhadrasan', 'name_bn' => 'চরভদ্রাসন', 'url' => 'charbhadrasan.faridpur.gov.bd'),
      array('id' => '397', 'district_id' => '52', 'name' => 'Madhukhali', 'name_bn' => 'মধুখালী', 'url' => 'madhukhali.faridpur.gov.bd'),
      array('id' => '398', 'district_id' => '52', 'name' => 'Saltha', 'name_bn' => 'সালথা', 'url' => 'saltha.faridpur.gov.bd'),
      array('id' => '399', 'district_id' => '53', 'name' => 'Panchagarh Sadar', 'name_bn' => 'পঞ্চগড় সদর', 'url' => 'panchagarhsadar.panchagarh.gov.bd'),
      array('id' => '400', 'district_id' => '53', 'name' => 'Debiganj', 'name_bn' => 'দেবীগঞ্জ', 'url' => 'debiganj.panchagarh.gov.bd'),
      array('id' => '401', 'district_id' => '53', 'name' => 'Boda', 'name_bn' => 'বোদা', 'url' => 'boda.panchagarh.gov.bd'),
      array('id' => '402', 'district_id' => '53', 'name' => 'Atwari', 'name_bn' => 'আটোয়ারী', 'url' => 'atwari.panchagarh.gov.bd'),
      array('id' => '403', 'district_id' => '53', 'name' => 'Tetulia', 'name_bn' => 'তেতুলিয়া', 'url' => 'tetulia.panchagarh.gov.bd'),
      array('id' => '404', 'district_id' => '54', 'name' => 'Nawabganj', 'name_bn' => 'নবাবগঞ্জ', 'url' => 'nawabganj.dinajpur.gov.bd'),
      array('id' => '405', 'district_id' => '54', 'name' => 'Birganj', 'name_bn' => 'বীরগঞ্জ', 'url' => 'birganj.dinajpur.gov.bd'),
      array('id' => '406', 'district_id' => '54', 'name' => 'Ghoraghat', 'name_bn' => 'ঘোড়াঘাট', 'url' => 'ghoraghat.dinajpur.gov.bd'),
      array('id' => '407', 'district_id' => '54', 'name' => 'Birampur', 'name_bn' => 'বিরামপুর', 'url' => 'birampur.dinajpur.gov.bd'),
      array('id' => '408', 'district_id' => '54', 'name' => 'Parbatipur', 'name_bn' => 'পার্বতীপুর', 'url' => 'parbatipur.dinajpur.gov.bd'),
      array('id' => '409', 'district_id' => '54', 'name' => 'Bochaganj', 'name_bn' => 'বোচাগঞ্জ', 'url' => 'bochaganj.dinajpur.gov.bd'),
      array('id' => '410', 'district_id' => '54', 'name' => 'Kaharol', 'name_bn' => 'কাহারোল', 'url' => 'kaharol.dinajpur.gov.bd'),
      array('id' => '411', 'district_id' => '54', 'name' => 'Fulbari', 'name_bn' => 'ফুলবাড়ী', 'url' => 'fulbari.dinajpur.gov.bd'),
      array('id' => '412', 'district_id' => '54', 'name' => 'Dinajpur Sadar', 'name_bn' => 'দিনাজপুর সদর', 'url' => 'dinajpursadar.dinajpur.gov.bd'),
      array('id' => '413', 'district_id' => '54', 'name' => 'Hakimpur', 'name_bn' => 'হাকিমপুর', 'url' => 'hakimpur.dinajpur.gov.bd'),
      array('id' => '414', 'district_id' => '54', 'name' => 'Khansama', 'name_bn' => 'খানসামা', 'url' => 'khansama.dinajpur.gov.bd'),
      array('id' => '415', 'district_id' => '54', 'name' => 'Birol', 'name_bn' => 'বিরল', 'url' => 'birol.dinajpur.gov.bd'),
      array('id' => '416', 'district_id' => '54', 'name' => 'Chirirbandar', 'name_bn' => 'চিরিরবন্দর', 'url' => 'chirirbandar.dinajpur.gov.bd'),
      array('id' => '417', 'district_id' => '55', 'name' => 'Lalmonirhat Sadar', 'name_bn' => 'লালমনিরহাট সদর', 'url' => 'sadar.lalmonirhat.gov.bd'),
      array('id' => '418', 'district_id' => '55', 'name' => 'Kaliganj', 'name_bn' => 'কালীগঞ্জ', 'url' => 'kaliganj.lalmonirhat.gov.bd'),
      array('id' => '419', 'district_id' => '55', 'name' => 'Hatibandha', 'name_bn' => 'হাতীবান্ধা', 'url' => 'hatibandha.lalmonirhat.gov.bd'),
      array('id' => '420', 'district_id' => '55', 'name' => 'Patgram', 'name_bn' => 'পাটগ্রাম', 'url' => 'patgram.lalmonirhat.gov.bd'),
      array('id' => '421', 'district_id' => '55', 'name' => 'Aditmari', 'name_bn' => 'আদিতমারী', 'url' => 'aditmari.lalmonirhat.gov.bd'),
      array('id' => '422', 'district_id' => '56', 'name' => 'Syedpur', 'name_bn' => 'সৈয়দপুর', 'url' => 'syedpur.nilphamari.gov.bd'),
      array('id' => '423', 'district_id' => '56', 'name' => 'Domar', 'name_bn' => 'ডোমার', 'url' => 'domar.nilphamari.gov.bd'),
      array('id' => '424', 'district_id' => '56', 'name' => 'Dimla', 'name_bn' => 'ডিমলা', 'url' => 'dimla.nilphamari.gov.bd'),
      array('id' => '425', 'district_id' => '56', 'name' => 'Jaldhaka', 'name_bn' => 'জলঢাকা', 'url' => 'jaldhaka.nilphamari.gov.bd'),
      array('id' => '426', 'district_id' => '56', 'name' => 'Kishorganj', 'name_bn' => 'কিশোরগঞ্জ', 'url' => 'kishorganj.nilphamari.gov.bd'),
      array('id' => '427', 'district_id' => '56', 'name' => 'Nilphamari Sadar', 'name_bn' => 'নীলফামারী সদর', 'url' => 'nilphamarisadar.nilphamari.gov.bd'),
      array('id' => '428', 'district_id' => '57', 'name' => 'Sadullapur', 'name_bn' => 'সাদুল্লাপুর', 'url' => 'sadullapur.gaibandha.gov.bd'),
      array('id' => '429', 'district_id' => '57', 'name' => 'Gaibandha Sadar', 'name_bn' => 'গাইবান্ধা সদর', 'url' => 'gaibandhasadar.gaibandha.gov.bd'),
      array('id' => '430', 'district_id' => '57', 'name' => 'Palashbari', 'name_bn' => 'পলাশবাড়ী', 'url' => 'palashbari.gaibandha.gov.bd'),
      array('id' => '431', 'district_id' => '57', 'name' => 'Saghata', 'name_bn' => 'সাঘাটা', 'url' => 'saghata.gaibandha.gov.bd'),
      array('id' => '432', 'district_id' => '57', 'name' => 'Gobindaganj', 'name_bn' => 'গোবিন্দগঞ্জ', 'url' => 'gobindaganj.gaibandha.gov.bd'),
      array('id' => '433', 'district_id' => '57', 'name' => 'Sundarganj', 'name_bn' => 'সুন্দরগঞ্জ', 'url' => 'sundarganj.gaibandha.gov.bd'),
      array('id' => '434', 'district_id' => '57', 'name' => 'Phulchari', 'name_bn' => 'ফুলছড়ি', 'url' => 'phulchari.gaibandha.gov.bd'),
      array('id' => '435', 'district_id' => '58', 'name' => 'Thakurgaon Sadar', 'name_bn' => 'ঠাকুরগাঁও সদর', 'url' => 'thakurgaonsadar.thakurgaon.gov.bd'),
      array('id' => '436', 'district_id' => '58', 'name' => 'Pirganj', 'name_bn' => 'পীরগঞ্জ', 'url' => 'pirganj.thakurgaon.gov.bd'),
      array('id' => '437', 'district_id' => '58', 'name' => 'Ranisankail', 'name_bn' => 'রাণীশংকৈল', 'url' => 'ranisankail.thakurgaon.gov.bd'),
      array('id' => '438', 'district_id' => '58', 'name' => 'Haripur', 'name_bn' => 'হরিপুর', 'url' => 'haripur.thakurgaon.gov.bd'),
      array('id' => '439', 'district_id' => '58', 'name' => 'Baliadangi', 'name_bn' => 'বালিয়াডাঙ্গী', 'url' => 'baliadangi.thakurgaon.gov.bd'),
      array('id' => '440', 'district_id' => '59', 'name' => 'Rangpur Sadar', 'name_bn' => 'রংপুর সদর', 'url' => 'rangpursadar.rangpur.gov.bd'),
      array('id' => '441', 'district_id' => '59', 'name' => 'Gangachara', 'name_bn' => 'গংগাচড়া', 'url' => 'gangachara.rangpur.gov.bd'),
      array('id' => '442', 'district_id' => '59', 'name' => 'Taragonj', 'name_bn' => 'তারাগঞ্জ', 'url' => 'taragonj.rangpur.gov.bd'),
      array('id' => '443', 'district_id' => '59', 'name' => 'Badargonj', 'name_bn' => 'বদরগঞ্জ', 'url' => 'badargonj.rangpur.gov.bd'),
      array('id' => '444', 'district_id' => '59', 'name' => 'Mithapukur', 'name_bn' => 'মিঠাপুকুর', 'url' => 'mithapukur.rangpur.gov.bd'),
      array('id' => '445', 'district_id' => '59', 'name' => 'Pirgonj', 'name_bn' => 'পীরগঞ্জ', 'url' => 'pirgonj.rangpur.gov.bd'),
      array('id' => '446', 'district_id' => '59', 'name' => 'Kaunia', 'name_bn' => 'কাউনিয়া', 'url' => 'kaunia.rangpur.gov.bd'),
      array('id' => '447', 'district_id' => '59', 'name' => 'Pirgacha', 'name_bn' => 'পীরগাছা', 'url' => 'pirgacha.rangpur.gov.bd'),
      array('id' => '448', 'district_id' => '60', 'name' => 'Kurigram Sadar', 'name_bn' => 'কুড়িগ্রাম সদর', 'url' => 'kurigramsadar.kurigram.gov.bd'),
      array('id' => '449', 'district_id' => '60', 'name' => 'Nageshwari', 'name_bn' => 'নাগেশ্বরী', 'url' => 'nageshwari.kurigram.gov.bd'),
      array('id' => '450', 'district_id' => '60', 'name' => 'Bhurungamari', 'name_bn' => 'ভুরুঙ্গামারী', 'url' => 'bhurungamari.kurigram.gov.bd'),
      array('id' => '451', 'district_id' => '60', 'name' => 'Phulbari', 'name_bn' => 'ফুলবাড়ী', 'url' => 'phulbari.kurigram.gov.bd'),
      array('id' => '452', 'district_id' => '60', 'name' => 'Rajarhat', 'name_bn' => 'রাজারহাট', 'url' => 'rajarhat.kurigram.gov.bd'),
      array('id' => '453', 'district_id' => '60', 'name' => 'Ulipur', 'name_bn' => 'উলিপুর', 'url' => 'ulipur.kurigram.gov.bd'),
      array('id' => '454', 'district_id' => '60', 'name' => 'Chilmari', 'name_bn' => 'চিলমারী', 'url' => 'chilmari.kurigram.gov.bd'),
      array('id' => '455', 'district_id' => '60', 'name' => 'Rowmari', 'name_bn' => 'রৌমারী', 'url' => 'rowmari.kurigram.gov.bd'),
      array('id' => '456', 'district_id' => '60', 'name' => 'Charrajibpur', 'name_bn' => 'চর রাজিবপুর', 'url' => 'charrajibpur.kurigram.gov.bd'),
      array('id' => '457', 'district_id' => '61', 'name' => 'Sherpur Sadar', 'name_bn' => 'শেরপুর সদর', 'url' => 'sherpursadar.sherpur.gov.bd'),
      array('id' => '458', 'district_id' => '61', 'name' => 'Nalitabari', 'name_bn' => 'নালিতাবাড়ী', 'url' => 'nalitabari.sherpur.gov.bd'),
      array('id' => '459', 'district_id' => '61', 'name' => 'Sreebordi', 'name_bn' => 'শ্রীবরদী', 'url' => 'sreebordi.sherpur.gov.bd'),
      array('id' => '460', 'district_id' => '61', 'name' => 'Nokla', 'name_bn' => 'নকলা', 'url' => 'nokla.sherpur.gov.bd'),
      array('id' => '461', 'district_id' => '61', 'name' => 'Jhenaigati', 'name_bn' => 'ঝিনাইগাতী', 'url' => 'jhenaigati.sherpur.gov.bd'),
      array('id' => '462', 'district_id' => '62', 'name' => 'Fulbaria', 'name_bn' => 'ফুলবাড়ীয়া', 'url' => 'fulbaria.mymensingh.gov.bd'),
      array('id' => '463', 'district_id' => '62', 'name' => 'Trishal', 'name_bn' => 'ত্রিশাল', 'url' => 'trishal.mymensingh.gov.bd'),
      array('id' => '464', 'district_id' => '62', 'name' => 'Bhaluka', 'name_bn' => 'ভালুকা', 'url' => 'bhaluka.mymensingh.gov.bd'),
      array('id' => '465', 'district_id' => '62', 'name' => 'Muktagacha', 'name_bn' => 'মুক্তাগাছা', 'url' => 'muktagacha.mymensingh.gov.bd'),
      array('id' => '466', 'district_id' => '62', 'name' => 'Mymensingh Sadar', 'name_bn' => 'ময়মনসিংহ সদর', 'url' => 'mymensinghsadar.mymensingh.gov.bd'),
      array('id' => '467', 'district_id' => '62', 'name' => 'Dhobaura', 'name_bn' => 'ধোবাউড়া', 'url' => 'dhobaura.mymensingh.gov.bd'),
      array('id' => '468', 'district_id' => '62', 'name' => 'Phulpur', 'name_bn' => 'ফুলপুর', 'url' => 'phulpur.mymensingh.gov.bd'),
      array('id' => '469', 'district_id' => '62', 'name' => 'Haluaghat', 'name_bn' => 'হালুয়াঘাট', 'url' => 'haluaghat.mymensingh.gov.bd'),
      array('id' => '470', 'district_id' => '62', 'name' => 'Gouripur', 'name_bn' => 'গৌরীপুর', 'url' => 'gouripur.mymensingh.gov.bd'),
      array('id' => '471', 'district_id' => '62', 'name' => 'Gafargaon', 'name_bn' => 'গফরগাঁও', 'url' => 'gafargaon.mymensingh.gov.bd'),
      array('id' => '472', 'district_id' => '62', 'name' => 'Iswarganj', 'name_bn' => 'ঈশ্বরগঞ্জ', 'url' => 'iswarganj.mymensingh.gov.bd'),
      array('id' => '473', 'district_id' => '62', 'name' => 'Nandail', 'name_bn' => 'নান্দাইল', 'url' => 'nandail.mymensingh.gov.bd'),
      array('id' => '474', 'district_id' => '62', 'name' => 'Tarakanda', 'name_bn' => 'তারাকান্দা', 'url' => 'tarakanda.mymensingh.gov.bd'),
      array('id' => '475', 'district_id' => '63', 'name' => 'Jamalpur Sadar', 'name_bn' => 'জামালপুর সদর', 'url' => 'jamalpursadar.jamalpur.gov.bd'),
      array('id' => '476', 'district_id' => '63', 'name' => 'Melandah', 'name_bn' => 'মেলান্দহ', 'url' => 'melandah.jamalpur.gov.bd'),
      array('id' => '477', 'district_id' => '63', 'name' => 'Islampur', 'name_bn' => 'ইসলামপুর', 'url' => 'islampur.jamalpur.gov.bd'),
      array('id' => '478', 'district_id' => '63', 'name' => 'Dewangonj', 'name_bn' => 'দেওয়ানগঞ্জ', 'url' => 'dewangonj.jamalpur.gov.bd'),
      array('id' => '479', 'district_id' => '63', 'name' => 'Sarishabari', 'name_bn' => 'সরিষাবাড়ী', 'url' => 'sarishabari.jamalpur.gov.bd'),
      array('id' => '480', 'district_id' => '63', 'name' => 'Madarganj', 'name_bn' => 'মাদারগঞ্জ', 'url' => 'madarganj.jamalpur.gov.bd'),
      array('id' => '481', 'district_id' => '63', 'name' => 'Bokshiganj', 'name_bn' => 'বকশীগঞ্জ', 'url' => 'bokshiganj.jamalpur.gov.bd'),
      array('id' => '482', 'district_id' => '64', 'name' => 'Barhatta', 'name_bn' => 'বারহাট্টা', 'url' => 'barhatta.netrokona.gov.bd'),
      array('id' => '483', 'district_id' => '64', 'name' => 'Durgapur', 'name_bn' => 'দুর্গাপুর', 'url' => 'durgapur.netrokona.gov.bd'),
      array('id' => '484', 'district_id' => '64', 'name' => 'Kendua', 'name_bn' => 'কেন্দুয়া', 'url' => 'kendua.netrokona.gov.bd'),
      array('id' => '485', 'district_id' => '64', 'name' => 'Atpara', 'name_bn' => 'আটপাড়া', 'url' => 'atpara.netrokona.gov.bd'),
      array('id' => '486', 'district_id' => '64', 'name' => 'Madan', 'name_bn' => 'মদন', 'url' => 'madan.netrokona.gov.bd'),
      array('id' => '487', 'district_id' => '64', 'name' => 'Khaliajuri', 'name_bn' => 'খালিয়াজুরী', 'url' => 'khaliajuri.netrokona.gov.bd'),
      array('id' => '488', 'district_id' => '64', 'name' => 'Kalmakanda', 'name_bn' => 'কলমাকান্দা', 'url' => 'kalmakanda.netrokona.gov.bd'),
      array('id' => '489', 'district_id' => '64', 'name' => 'Mohongonj', 'name_bn' => 'মোহনগঞ্জ', 'url' => 'mohongonj.netrokona.gov.bd'),
      array('id' => '490', 'district_id' => '64', 'name' => 'Purbadhala', 'name_bn' => 'পূর্বধলা', 'url' => 'purbadhala.netrokona.gov.bd'),
      array('id' => '491', 'district_id' => '64', 'name' => 'Netrokona Sadar', 'name_bn' => 'নেত্রকোণা সদর', 'url' => 'netrokonasadar.netrokona.gov.bd')
    );

    \Illuminate\Support\Facades\DB::table(with(new Upazila)->getTable())->insert($upazilas);
  }

  /**
   * Reverse the migrations.
   *
   * @return void
   */
  public function down()
  {
    Schema::dropIfExists(with(new Upazila)->getTable());
  }
};
